# SPDX-License-Identifier: GPL-2.0+
obj-$(CONFIG_BACKLIGHT_LM3533) += lm3533_backlight.o
obj-$(CONFIG_BRIDGE_SOLOMON_SSD2825) += ssd2825.o
obj-$(CONFIG_BRIDGE_SPI) += bridge-spi.o
obj-$(CONFIG_PANEL_KOE_TX13D100VM0EAA) += koe-tx13d100vm0eaa.o
obj-$(CONFIG_PANEL_RENESAS_R69328) += renesas-r69328.o
